# Basic Operations in TensorFlow

This notebook is basically a clone of Stanford CS20 Introduction to Tensorflow  ->   [here](https://docs.google.com/document/d/1FSPNZFQsnaUVeTo0OQ2RrEZ0f4el9bIGI5sQALbG_F0/edit#)

### Agenda
- Basic Operations
- Tensor types
- Importing data
- Lazy loading

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.8.0'

### Recap on Last Class

#### APIs
- Low Level (core) APIs e.g `Tensors` `Graphs` `Sessions`
- High Level APIs e.g `tf.estimators` `tf.Datasets`

#### Tensors
Tensors -> Basic data structure in TensorFlow which stores data in any number of dimensions. We can have
- Constants -> Immutable tensors which can be seen as nodes without inputs, outputting a single value they store internally.
- Variables -> Mutable tensors whose value can change during a run of a graph. Variables stores the paramenters which needs to be optimized (e.g weights). Variables needs to be initialized before running the graph by explicitly calling a special operation.
- Placeholders -> Tensors that store data from external sources. They represent a "promise' that a value will be provided when the graph is run. They are usually used (in ML applications) for inoutting data to the learning model.

#### Sessions
Encapsulates the environment where your graph operations is executed and Tensor Objects evaluated.

#### Computational Graphs
Series of TensorFlow Ops. It consists of Tensor Objects and Operator Objects.

In [3]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)

In [4]:
with tf.Session() as sess:
    print (sess.run(c))

5


Got Warning?<br>
```The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.```

add <br>
`import os` <br>
`os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'`

------------

### Visualize with Tensorboard

Tensorboard is used to understand, debug, and optimize TensorFlow programs

In [8]:
# Create a summary writer after graph definition
writer = tf.summary.FileWriter('./graphs/operations', tf.get_default_graph())

In [9]:
# Close writer when done
writer.close()

In [10]:
# Check to see if their's graphs folder
! ls graphs/operations

events.out.tfevents.1527549567.sensei-HP-ProBook-4530s


In [11]:
# Uncomment and Run this 
# You have to terminate once you're done visualizing or simply run on your CMD
# ! tensorboard --logdir='./graphs/operations' --port 6006

### Named variables


In [12]:
x = tf.constant(2, name='x')
y = tf.constant(3, name='y')
z = tf.add(x, y, name='add')

In [13]:
with tf.Session() as sess:
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(x))
writer.close()

2


In [14]:
# Run
# ! tensorboard --logdir='./graphs' --port 6006

In [15]:
# graph = tf.get_default_graph()
# for op in graph.get_operations():
#     print(op.name)

#### Constants, Sequences, Variables, Ops

In [16]:
# constant of 1d tensor(vector)
a = tf.constant([2, 2], name="vector")

# constant of 2x2 tensor(matrix)
b = tf.constant([[0, 1], [2,3]], name='matrix')


In [17]:
# tensors of specific dimension
# tf.zeros(shape, dtype=tf.float32, name=None)
c = tf.zeros([2,3], tf.int32)

# zeros_like tensors
# tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
input_tensor = tf.constant([[0,1], [2,3], [4,5]])
d = tf.zeros_like(input_tensor)

In [18]:
input_tensor.get_shape()

TensorShape([Dimension(3), Dimension(2)])

In [19]:
# setup an interactive session
sess = tf.InteractiveSession()


In [20]:
sess.run(c)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [21]:
d.eval()

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [22]:
# tf.ones(shape, dtype=tf.float32, name=None)
e = tf.ones([2,3], tf.int32)

# tf.ones_like(input_tensor, dtype=None, optimize=True)
f = tf.ones_like(input_tensor)

In [23]:
e.eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [24]:
f.eval()

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [25]:
# create tensor filled with scalar value
# tf.fill(dims, value, name=None)
g = tf.fill([2,3], 8)

In [26]:
g.eval()

array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [27]:
# Create constants that are sequences -> evenly spaced values
# tf.lin_space(start, stop, num, name=None)
h = tf.lin_space(0.0, 10.0, 5, name='linspace')

# comparable to  numpy.linspace

In [28]:
h.eval()

array([ 0. ,  2.5,  5. ,  7.5, 10. ], dtype=float32)

In [29]:
# tf.range([start], limit=None, delta=1, dtype=None, name='range')
i = tf.range(3, 8, 3)
j = tf.range(3, 1, -0.5)
k = tf.range(3)

In [30]:
i.eval()

array([3, 6], dtype=int32)

In [31]:
j.eval()

array([3. , 2.5, 2. , 1.5], dtype=float32)

In [32]:
k.eval()

array([0, 1, 2], dtype=int32)

In [33]:
# Unlike Numpy or Python, TensorFlow sequences are not iterable.
# for _ in np.linspace(0, 10,  4) works
# for _ in tf.linspace(0, 10, 4) gives TypeError "Tensor" object is not iterable

# for _ in range(4) works
# for _ in tf.range(4) TypeError: 'Tensor' object is not iterable


In [35]:
# Generate random constants
# tf.random_normal
# tf.truncated_normal
# tf.random_uniform
# tf.random_shuffle
# tf.random_crop
# tf.multinomial
# tf.random_gamma
# tf.set_random_seed

In [36]:
# Close the Interactive Session
sess.close()

some more examles [here](https://www.tensorflow.org/api_guides/python/constant_op)

#### Math operations
A full list can be viewed [here](https://www.tensorflow.org/api_guides/python/math_ops)

In [37]:
# tf.add()
# tf.subtract()
# tf.multiply()

Let's see tf's different division

In [40]:
# tf.div
# tf.divide
# tf.truediv
# tf.floordiv
# tf.realdiv
# tf.truncatediv
# tf.floor_div

The functions do more or less the same thing but one thing worthy of note is that `tf.div` does TensorFlow type of division while `tf.divide` does Python stype of division - well, this ofcourse depends on which python version we're talking about :-)

In [41]:
# example
a = tf.constant([2,2], name='a')
b = tf.constant([[0,1],[2,3]], name='b')

with tf.Session() as sess:
    print(sess.run(tf.div(b,a)))
    print(sess.run(tf.divide(b,a)))
    print(sess.run(tf.truediv(b,a)))
    print(sess.run(tf.floordiv(b,a)))
    print(sess.run(tf.truncatediv(b,a)))
    print(sess.run(tf.floor_div(b,a)))
    #     print(sess.run(tf.realdiv(b,a))) # err, real values only

[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


In [42]:
# tf.add_n allows you to add multiple tensors
l = tf.add_n([b,b,b])

#### Dot product in TensorFlow
Note: `tf.matmul` no longer does dot product. It multiplies matrices of rank greater than or equal to 2. Use `tf.tensordot` to do dot product

In [43]:
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')
with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b)))
    print(sess.run(tf.tensordot(a, b, axes=1)))
#     print(sess.run(tf.matmul(a,b))) # err "shape" must be rank 2 or greater

[20 60]
80


In [44]:
# print graph definition
print(tf.get_default_graph().as_graph_def())

node {
  name: "Const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "Const_1"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 3
      }
    }
  }
}
node {
  name: "Add"
  op: "Add"
  input: "Const"
  input: "Const_1"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
node {
  name: "x"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "y"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }

#### Creating Variables


In [ ]:
# note tf.Variable is a class with multiply ops ans that's why it begins with "V" instead f "v"
# x = tf/Variable(...)
# x.initializer - init
# x.value - read value
# x.assign - write op
# x.assign_add(...)
# and more

In [45]:
# Old way
s = tf.Variable(2, name="scalar")
m = tf.Variable([[0, 1], [2,3]], name="matrix")
W = tf.Variable(tf.zeros([784, 10]))

In [46]:
s = tf.get_variable("scalar", initializer=tf.constant(2))
m = tf.get_variable("matrix", initializer=tf.constant([[0,1],[2,3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())


#### Initialize Variables
You have to initialize a variable before using it. Attempting to use an uninitialized variables gets you a `FailedPreconditionError`

In [48]:
# list uninitialized variables
with tf.Session() as sess:
    print(tf.report_uninitialized_variables().eval())

[b'scalar' b'matrix_1' b'Variable' b'scalar_1' b'matrix_2' b'big_matrix']


In [49]:
# initialize all variable at a go
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

In [50]:
# intialize only a subset of variables using tf.variables_initializer()
with tf.Session() as sess:
    sess.run(tf.variables_initializer([s, m]))

In [51]:
# you can also intitialize a variable separately using tf.Variable.initializer
with tf.Session() as sess:
    sess.run(W.initializer)

#### Evaluate values of variables

In [52]:
V = tf.get_variable('normal_matrix', shape=(784, 10),
                   initializer=tf.truncated_normal_initializer())
print(V)

<tf.Variable 'normal_matrix:0' shape=(784, 10) dtype=float32_ref>


In [53]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(V))

[[ 0.45909056  0.7265281   0.3745594  ... -0.00273643  0.7478235
   0.19538353]
 [-0.8084524  -0.50677824 -0.916895   ... -0.56532747  1.170223
   0.5497768 ]
 [ 0.60375565  0.79252654 -0.02752771 ... -0.60150456 -0.7875073
  -1.6271254 ]
 ...
 [-0.56034297  1.6314656  -1.3034995  ... -0.17364447 -0.5641218
  -1.5152881 ]
 [ 0.10434577  0.5336016  -0.3562677  ... -0.44888866  0.30335647
   0.17051323]
 [-0.04083937 -1.1510079  -0.41877896 ...  0.86520696  0.3936505
   1.2420012 ]]


#### Assiging  Values to Variables

In [54]:
W = tf.Variable(10)
W.assign(100) # does not assign value to W but create an assign op
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval())

10


In [55]:
W = tf.get_variable('Variable2',initializer=10) # or tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    # note No initialization ? assign() does initialization for us
    sess.run(assign_op)
    print(W.eval())

100


Buzzer! In fact, the initializer op is an assign op that assigns the variable's initial value to the variable itself.


```self._initializer_op = state_ops.assign(self._variable, self._initial_value,                                                                   validate_shape=validate_shape).op```

We also have ops for incrementing or decrementing variables `tf.Variable.assign_add()`, `tf.Variable.assign_sub`, but unlike `tf.Variable.assign()` the afore-mentioned don't initialize your variables because they depend on the initial values of the variable

Also because Tensorflow sessions maintain values separetely, each Session van have its own value for a variable defined in a graph.

In [56]:
W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(W.initializer)
sess2.run(W.initializer)
print(sess1.run(W.assign_add(10)))
print(sess2.run(W.assign_sub(2)))
print(sess1.run(W.assign_add(100)))
sess1.close()
sess2.close()

20
8
120


#### Initialize variables that depend on another before use

In [57]:
W  = tf.Variable(tf.truncated_normal([700, 10]))
# U = tf.Variable(W * 2)
U = tf.Variable(W.initialized_value() * 2)

In [ ]:
sess = tf.Interactive

In [58]:
tf.get_default_session()

#### Control Dependencies
Sometimes, we might have two or more independent ops and we'd like to specify which ops should run first. `tf.Graph.control_dependencies([control_inputs])`

In [ ]:
# if your graph g has 5 ops: a, b, c, d, e
# with g.control_dependencies([a, b, c]):
    # d and e will only run after a, b and c have been executed
#     d = ...
#     e = ...

#### Importing Data


a. The Old way: Placeholders and feed_dict

In [ ]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)
c = a+b
with tf.Session() as sess:
    print(sess.run(c, {a: [1,2,3]}))

In [ ]:
# check what it looks like on tensorboard
writer = tf.summary.FileWriter('graphs/placeholders', tf.get_default_graph())
! tensorboard --logdir="graphs/placeholders"

In [ ]:
# use `tf.Graph.is_feedable(tensor)` to check if tensor is feedable or not

In [ ]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)

with tf.Session() as sess:
    print(sess.run(b))
    print(sess.run(b, feed_dict={a: 15}))

b. The New Way

To be discussed next class